version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      TANGIA_LOGS: "1"
      EULA: "TRUE"
      VERSION: "1.21.4"
      TYPE: PAPER
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./mcserver:/data
