version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      TANGIA_ENV: "STAGING"
      EULA: "TRUE"
      VERSION: "1.19.2"
      TYPE: SPIGOT
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      OPS: hades32de
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./mcserver:/data
